name: ci

on:
  push:
  pull_request:
  workflow_dispatch:


# Cancel in progress workflows
# in the scenario where we already had a run going for that PR/branch/tag but then triggered a new run
concurrency:
  group: "${{ github.workflow }} ✨ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name:
        - Node.js 0.10
        - Node.js 0.12
        - io.js 1.x
        - io.js 2.x
        - io.js 3.x
        - Node.js 4.x
        - Node.js 5.x
        - Node.js 6.x
        - Node.js 7.x
        - Node.js 8.x
        - Node.js 9.x
        - Node.js 10.x
        - Node.js 11.x
        - Node.js 12.x
        - Node.js 13.x
        - Node.js 14.x
        - Node.js 15.x
        - Node.js 16.x
        - Node.js 17.x
        - Node.js 18.x
        - Node.js 19.x
        - Node.js 20.x
        - Node.js 21.x
        - Node.js 22.x

        include:
        - name: Node.js 0.10
          node-version: "0.10"

        - name: Node.js 0.12
          node-version: "0.12"

        - name: io.js 1.x
          node-version: "1"

        - name: io.js 2.x
          node-version: "2"

        - name: io.js 3.x
          node-version: "3"

        - name: Node.js 4.x
          node-version: "4"

        - name: Node.js 5.x
          node-version: "5"

        - name: Node.js 6.x
          node-version: "6"

        - name: Node.js 7.x
          node-version: "7"

        - name: Node.js 8.x
          node-version: "8"

        - name: Node.js 9.x
          node-version: "9"

        - name: Node.js 10.x
          node-version: "10"

        - name: Node.js 11.x
          node-version: "11"

        - name: Node.js 12.x
          node-version: "12"
          npm-i: mocha@9.2.2

        - name: Node.js 13.x
          node-version: "13"

        - name: Node.js 14.x
          node-version: "14"

        - name: Node.js 15.x
          node-version: "15"

        - name: Node.js 16.x
          node-version: "16"

        - name: Node.js 17.x
          node-version: "17"

        - name: Node.js 18.x
          node-version: "18"

        - name: Node.js 19.x
          node-version: "19"

        - name: Node.js 20.x
          node-version: "20"

        - name: Node.js 21.x
          node-version: "21"

        - name: Node.js 22.x
          node-version: "22"

    steps:
    - uses: actions/checkout@v4

    - name: Install Node.js ${{ matrix.node-version }}
      shell: bash -eo pipefail -l {0}
      run: |
        nvm install --default ${{ matrix.node-version }}
        dirname "$(nvm which ${{ matrix.node-version }})" >> "$GITHUB_PATH"

    - name: Install Node.js dependencies
      run: npm install

    - name: List environment
      id: list_env
      shell: bash
      run: |
        echo "node@$(node -v)"
        echo "npm@$(npm -v)"
        npm -s ls ||:
        (npm -s ls --depth=0 ||:) | awk -F'[ @]' 'NR>1 && $2 { print $2 "=" $3 }' >> "$GITHUB_OUTPUT"

    - name: Run tests
      shell: bash
      run: |
        npm test
